apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: okdtemplates.odra.org
spec:
  group: odra.org
  names:
    kind: OKDTemplate
    listKind: OKDTemplateList
    plural: okdtemplates
    singular: okdtemplate
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
